// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFTwYpuR3qLyO6-AkNhu_zolKTOvYyxIk',
    appId: '1:174998332382:web:942d8189f7d7641c14734f',
    messagingSenderId: '174998332382',
    projectId: 'willcooks-557a7',
    authDomain: 'willcooks-557a7.firebaseapp.com',
    storageBucket: 'willcooks-557a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrxG1PEzO8bHy8n4ZQaEOE5FLJcYCll8E',
    appId: '1:174998332382:android:9b79f1c7543650bf14734f',
    messagingSenderId: '174998332382',
    projectId: 'willcooks-557a7',
    storageBucket: 'willcooks-557a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT4y1fdSGnm0oQ6F2GrmJRuE3ezUK809U',
    appId: '1:174998332382:ios:81fa212d9147db4714734f',
    messagingSenderId: '174998332382',
    projectId: 'willcooks-557a7',
    storageBucket: 'willcooks-557a7.firebasestorage.app',
    iosBundleId: 'com.example.flutterprojects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT4y1fdSGnm0oQ6F2GrmJRuE3ezUK809U',
    appId: '1:174998332382:ios:81fa212d9147db4714734f',
    messagingSenderId: '174998332382',
    projectId: 'willcooks-557a7',
    storageBucket: 'willcooks-557a7.firebasestorage.app',
    iosBundleId: 'com.example.flutterprojects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFTwYpuR3qLyO6-AkNhu_zolKTOvYyxIk',
    appId: '1:174998332382:web:07c192d5c3c911cc14734f',
    messagingSenderId: '174998332382',
    projectId: 'willcooks-557a7',
    authDomain: 'willcooks-557a7.firebaseapp.com',
    storageBucket: 'willcooks-557a7.firebasestorage.app',
  );
}
